name: chefmeprime
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
 sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  fluentui_icons: ^1.0.0
  flutter_native_splash: ^2.4.1
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.3
  provider: ^6.1.2
  image_picker: ^1.1.2
  popover: ^0.3.1
  url_launcher: ^6.3.0
  animated_splash_screen: ^1.3.0

flutter_native_splash:
  android: true
  ios: true

  color: "#000000"
  image: assets/linkedin.png
  android_12:
   color: "#000000"
   image: assets/linkedin.png



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
 

    

flutter:
  uses-material-design: true
  assets:
    - assets/